In [4]:
import numpy as np
import pandas as pd

#### 1.	Create a 2D array and print the dim and shape

In [13]:
# Creating 2D array
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Printing shape
print('Array Dimension:',array1.ndim)

# Printing dimension of the array
print('Array Shape(Rows,Columns):',array1.shape)

Array Dimension: 2
Array Shape(Rows,Columns): (3, 3)


#### 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [19]:
# Creating array with 20 numbers range
array2 = np.arange(20)

# Printing the array
print(array2)

# Slicing the array to print 10 to 15 numbers
array2[10:16]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([10, 11, 12, 13, 14, 15])

#### 3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 
a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [97]:
# Creating first array with 7X5 dimension
a1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])

# Creating second array with 7X5 dimension
a2 = np.array([[35,34,33,32,31],[30,29,28,27,26],[25,24,23,22,21],[20,19,18,17,16],[15,14,13,12,11],[10,9,8,7,6],[5,4,3,2,1]])


In [98]:
# a. Addition of a1 and a2
print('Addition Result: ',np.add(a1,a2))


Addition Result:  [[36 36 36 36 36]
 [36 36 36 36 36]
 [36 36 36 36 36]
 [36 36 36 36 36]
 [36 36 36 36 36]
 [36 36 36 36 36]
 [36 36 36 36 36]]


In [99]:
# b. Subtraction of a1 and a2
print('Subtraction Result: ',np.subtract(a1,a2))


Subtraction Result:  [[-34 -32 -30 -28 -26]
 [-24 -22 -20 -18 -16]
 [-14 -12 -10  -8  -6]
 [ -4  -2   0   2   4]
 [  6   8  10  12  14]
 [ 16  18  20  22  24]
 [ 26  28  30  32  34]]


In [100]:
# c. Multiplication of a1 and a2
print('Multiplication Result: ',np.multiply(a1,a2))


Multiplication Result:  [[ 35  68  99 128 155]
 [180 203 224 243 260]
 [275 288 299 308 315]
 [320 323 324 323 320]
 [315 308 299 288 275]
 [260 243 224 203 180]
 [155 128  99  68  35]]


In [101]:
# d. Division of a1 and a2
print('Division Result: ',np.divide(a1,a2))

Division Result:  [[2.85714286e-02 5.88235294e-02 9.09090909e-02 1.25000000e-01
  1.61290323e-01]
 [2.00000000e-01 2.41379310e-01 2.85714286e-01 3.33333333e-01
  3.84615385e-01]
 [4.40000000e-01 5.00000000e-01 5.65217391e-01 6.36363636e-01
  7.14285714e-01]
 [8.00000000e-01 8.94736842e-01 1.00000000e+00 1.11764706e+00
  1.25000000e+00]
 [1.40000000e+00 1.57142857e+00 1.76923077e+00 2.00000000e+00
  2.27272727e+00]
 [2.60000000e+00 3.00000000e+00 3.50000000e+00 4.14285714e+00
  5.00000000e+00]
 [6.20000000e+00 8.00000000e+00 1.10000000e+01 1.70000000e+01
  3.50000000e+01]]


#### 4.	Create 2 incompatible arrays for broadcast and print out the error

In [30]:
# Creating first array with shape(2,3)
ar1 = np.array([[1,3,2],[4,5,6]])

# Creating second array with shape(2,2)
ar2 = np.array([[1,2],[4,5]])

# Trying to broadcast the arrays with different shapes
ar1*ar2

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### 5.	Create two arrays of any dimension and perform vstack and hstack

In [38]:
# Creating first array
arr1 = np.array([[1,2,3,4,5],['Six','Seven','Eight',9,10]])

# Creating second array
arr2 = np.array([[1,'Two',3,4,'Five'],[6,7,'Eight',9,10]])

# Performing vstack
print('VStack Result:',np.vstack((arr1,arr2)))

# Performing hstack
print('HStack Result:',np.hstack((arr1,arr2)))

VStack Result: [['1' '2' '3' '4' '5']
 ['Six' 'Seven' 'Eight' '9' '10']
 ['1' 'Two' '3' '4' 'Five']
 ['6' '7' 'Eight' '9' '10']]
HStack Result: [['1' '2' '3' '4' '5' '1' 'Two' '3' '4' 'Five']
 ['Six' 'Seven' 'Eight' '9' '10' '6' '7' 'Eight' '9' '10']]


#### 6.	Append two arrays using axis = 0 and axis = 1

In [45]:
# Creating first array
arra1 = np.array([[1,2,3,4,5],['Six','Seven','Eight',9,10]])

# Creating second array
arra2 = np.array([[1,'Two',3,4,'Five'],[6,7,'Eight',9,10]])

# Performing append with axis = 0
print(np.append(arra1,arra2, axis=0))

# Performing append with axis = 1
print(np.append(arra1,arra2, axis=1))

[['1' '2' '3' '4' '5']
 ['Six' 'Seven' 'Eight' '9' '10']
 ['1' 'Two' '3' '4' 'Five']
 ['6' '7' 'Eight' '9' '10']]
[['1' '2' '3' '4' '5' '1' 'Two' '3' '4' 'Five']
 ['Six' 'Seven' 'Eight' '9' '10' '6' '7' 'Eight' '9' '10']]


#### 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [52]:
# Creating data array with 8X4 dimension
dfArray = np.array([['Polo','Volkswagon','India',2400],['Fiesta','Ford','Japan',4500],['GLC Deluxe','Mazda','Malaysia',4000],['Beat','Chevrolet','Singapore',6700],['Corona','Toyota','Korea',7800],['Creta','Hyundai','USA',5200],['Venue','Hyundai','Germany',1200],['Seltos','Kia','Korea',4500]])

# Creating dataframe for the array data
df1 = pd.DataFrame(dfArray,columns=['Model','Brand','Country','Price'])

# Printing dataframe
df1

Model       Brand    Country Price
0        Polo  Volkswagon      India  2400
1      Fiesta        Ford      Japan  4500
2  GLC Deluxe       Mazda   Malaysia  4000
3        Beat   Chevrolet  Singapore  6700
4      Corona      Toyota      Korea  7800
5       Creta     Hyundai        USA  5200
6       Venue     Hyundai    Germany  1200
7      Seltos         Kia      Korea  4500

#### 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [55]:
# Creating data array with 8X4 dimension
dfArray1 = {'Model':['Polo','Creta','Beat','Fiesta'],
           'Brand':['Volkswagon','Hyundai','Chevrolet','Ford'],
           'Country':['India','Japan','Korea','Singapore'],
           'Cost':[2100,5300,6500,2100],
           'Miles per Gallon':[43.1,52.1,23.2,65.4],
           'Acceleration':[21.5,32.5,15.2,25.4],
           'HorsePower':[48,66,120,100],
           'Cylinders':[4,6,8,4]}

# Creating dataframe for the array data
df2 = pd.DataFrame(dfArray1)

# Printing dataframe
df2

Model       Brand    Country  Cost  Miles per Gallon  Acceleration  \
0    Polo  Volkswagon      India  2100              43.1          21.5   
1   Creta     Hyundai      Japan  5300              52.1          32.5   
2    Beat   Chevrolet      Korea  6500              23.2          15.2   
3  Fiesta        Ford  Singapore  2100              65.4          25.4   

   HorsePower  Cylinders  
0          48          4  
1          66          6  
2         120          8  
3         100          4

#### 9.	Use loc and iloc to subset the data for the above dataframe

In [64]:
# Implementing loc to get subset of first 2 records of df2
df3 = df2.loc[:1]

# printing resulted dataframe
df3

Model       Brand Country  Cost  Miles per Gallon  Acceleration  \
0   Polo  Volkswagon   India  2100              43.1          21.5   
1  Creta     Hyundai   Japan  5300              52.1          32.5   

   HorsePower  Cylinders  
0          48          4  
1          66          6

In [65]:
# Implementing iloc to get subset of 2,3 records of df2
df4 = df2.iloc[1:3]

# printing resulted dataframes
df4

Model      Brand Country  Cost  Miles per Gallon  Acceleration  HorsePower  \
1  Creta    Hyundai   Japan  5300              52.1          32.5          66   
2   Beat  Chevrolet   Korea  6500              23.2          15.2         120   

   Cylinders  
1          6  
2          8

#### 10.	How to check the total number of not null values in a column?

In [71]:
# Getting total number of not null values in the columns
print(df2['Model'].notnull().sum())

print(df1['Brand'].notnull().sum())

4
8


#### 11.	Create a dataframe with missing values and fill them all with 100

In [84]:
# Creating data Array with null values
dfArray2 = {'Variable':['Actual Bed','Chronic Bed','Physician','Pharmacist','Nursing Staff','Medical Staff'],
           'Specialist Hospital':[41,60,25,20,np.nan,50],
           'Chronic Hospital':[41,np.nan,25,np.nan,np.nan,50],
           'General Hospital':[np.nan,60,25,np.nan,np.nan,50]}

# Creating dataframe for the data frame
df5 = pd.DataFrame(dfArray2)

# Filling all null values of dataframe with 100
df5.fillna(100,inplace=True)
df5

Variable  Specialist Hospital  Chronic Hospital  General Hospital
0     Actual Bed                 41.0              41.0             100.0
1    Chronic Bed                 60.0             100.0              60.0
2      Physician                 25.0              25.0              25.0
3     Pharmacist                 20.0             100.0             100.0
4  Nursing Staff                100.0             100.0             100.0
5  Medical Staff                 50.0              50.0              50.0

#### 12.	Create a dataframe with missing values and drop the null records

In [93]:
# Creating data Array
dfArray3 = [['1001',50,60,100,20],['1002',75,66,95,40],['1005',85,65,95,40],['1008',75,88,95,40],['1010',75,70,78,40]]

# Creating data frame for the array
df6 = pd.DataFrame(dfArray3,index=[1001,1002,1005,1008,1010],columns=['StudentId','Maths','Physics','Chemistry','English'])

# Creating records with missing ids in between the existing records
df6.reindex(range(1001,1010))

StudentId  Maths  Physics  Chemistry  English
1001      1001   50.0     60.0      100.0     20.0
1002      1002   75.0     66.0       95.0     40.0
1003       NaN    NaN      NaN        NaN      NaN
1004       NaN    NaN      NaN        NaN      NaN
1005      1005   85.0     65.0       95.0     40.0
1006       NaN    NaN      NaN        NaN      NaN
1007       NaN    NaN      NaN        NaN      NaN
1008      1008   75.0     88.0       95.0     40.0
1009       NaN    NaN      NaN        NaN      NaN

In [91]:
# Dropping null values
df6.dropna()

StudentId  Maths  Physics  Chemistry  English
1001      1001     50       60        100       20
1002      1002     75       66         95       40
1005      1005     85       65         95       40
1008      1008     75       88         95       40
1010      1010     75       70         78       40

#### 13.	Perform following aggregation task on below table
a.	Get the average age group by Region
b.	Get the sum of Age and Validation group by Hair color and then reset the index
c.	Get the man and the median of Age group by Region

In [96]:
# Creating data array for the below mentioned table
dfArray4 = {'Age':[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
            'Hair Color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
            'US Region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
            'Validation':[1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]  }

# Cteating data frame for the array
df7 = pd.DataFrame(dfArray4)


Age Hair Color  US Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [109]:
# a. Get the average age group by Region
df7.groupby(['US Region'])['Age'].mean()

US Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [106]:
# b. Get the sum of Age and Validation group by Hair color and then reset the index
df7.groupby(['Hair Color']).sum().reset_index()

Hair Color  Age  Validation
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

In [110]:
# c. Get the mean and the median of Age group by Region
df7.groupby(['US Region'])['Age'].mean()

US Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [111]:
df7.groupby(['US Region'])['Age'].median()

US Region
Northeast    31.0
Northwest    40.5
Southeast    25.5
Southwest    25.0
Name: Age, dtype: float64

#### 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [198]:
# Splitting data frame df7 in to two dataframes
df8 = df7.loc[:7]
df9 = df7.loc[8:]

In [199]:
# First split data frame
df8.reset_index(inplace=True)
df8

index  Age Hair Color  US Region  Validation
0      0   25      Black  Southwest           1
1      1   30      Black  Northwest           1
2      2   45        Red  Northeast           1
3      3   35      Blond  Southwest           0
4      4   33      Brown  Southwest           0
5      5   35      Brown  Northeast           0
6      6   25      Black  Southwest           0
7      7   52      Brown  Southeast           0

In [200]:
# Second split data frame
df9.reset_index(inplace=True)
df9

index  Age Hair Color  US Region  Validation
0      8   21      Blond  Southwest           1
1      9   24      Blond  Northeast           0
2     10   48      Black  Southwest           1
3     11   22      Black  Southwest           0
4     12   27      Brown  Northeast           0
5     13   28      Black  Southeast           1
6     14   21      Blond  Southeast           1
7     15   51      Black  Northwest           0
8     16   23      Brown  Southeast           1

In [201]:
# Merging dataframes # inner
dfInner = df8.merge(df9, on='US Region', how='inner')
dfInner

index_x  Age_x Hair Color_x  US Region  Validation_x  index_y  Age_y  \
0         0     25        Black  Southwest             1        8     21   
1         0     25        Black  Southwest             1       10     48   
2         0     25        Black  Southwest             1       11     22   
3         3     35        Blond  Southwest             0        8     21   
4         3     35        Blond  Southwest             0       10     48   
5         3     35        Blond  Southwest             0       11     22   
6         4     33        Brown  Southwest             0        8     21   
7         4     33        Brown  Southwest             0       10     48   
8         4     33        Brown  Southwest             0       11     22   
9         6     25        Black  Southwest             0        8     21   
10        6     25        Black  Southwest             0       10     48   
11        6     25        Black  Southwest             0       11     22   
12        1     30        Black  Northwest             1       15     51   
13        2     45          Red  Northeast             1        9     24   
14        2     45          Red  Northeast             1       12     27   
15        5     35        Brown  Northeast             0        9     24   
16        5     35        Brown  Northeast             0       12     27   
17        7     52        Brown  Southeast             0       13     28   
18        7     52        Brown  Southeast             0       14     21   
19        7     52        Brown  Southeast             0       16     23   

   Hair Color_y  Validation_y  
0         Blond             1  
1         Black             1  
2         Black             0  
3         Blond             1  
4         Black             1  
5         Black             0  
6         Blond             1  
7         Black             1  
8         Black             0  
9         Blond             1  
10        Black             1  
11        Black             0  
12        Black             0  
13        Blond             0  
14        Brown             0  
15        Blond             0  
16        Brown             0  
17        Black             1  
18        Blond             1  
19        Brown             1

In [202]:
# Merging dataframes # left
dfLeft = df9.merge(df10, on='US Region', how='left')
dfLeft

index  Age_x Hair Color_x  US Region  Validation_x  Age_y Hair Color_y  \
0       8     21        Blond  Southwest             1    NaN          NaN   
1       9     24        Blond  Northeast             0   27.0        Brown   
2      10     48        Black  Southwest             1    NaN          NaN   
3      11     22        Black  Southwest             0    NaN          NaN   
4      12     27        Brown  Northeast             0   27.0        Brown   
5      13     28        Black  Southeast             1   28.0        Black   
6      13     28        Black  Southeast             1   21.0        Blond   
7      13     28        Black  Southeast             1   23.0        Brown   
8      14     21        Blond  Southeast             1   28.0        Black   
9      14     21        Blond  Southeast             1   21.0        Blond   
10     14     21        Blond  Southeast             1   23.0        Brown   
11     15     51        Black  Northwest             0   51.0        Black   
12     16     23        Brown  Southeast             1   28.0        Black   
13     16     23        Brown  Southeast             1   21.0        Blond   
14     16     23        Brown  Southeast             1   23.0        Brown   

    Validation_y  
0            NaN  
1            0.0  
2            NaN  
3            NaN  
4            0.0  
5            1.0  
6            1.0  
7            1.0  
8            1.0  
9            1.0  
10           1.0  
11           0.0  
12           1.0  
13           1.0  
14           1.0

In [203]:
# Merging dataframes # right
dfRight = df10.merge(df8, on='US Region', how='right')
dfRight

Age_x Hair Color_x  US Region  Validation_x  index  Age_y Hair Color_y  \
0    NaN          NaN  Southwest           NaN      0     25        Black   
1   51.0        Black  Northwest           0.0      1     30        Black   
2   27.0        Brown  Northeast           0.0      2     45          Red   
3    NaN          NaN  Southwest           NaN      3     35        Blond   
4    NaN          NaN  Southwest           NaN      4     33        Brown   
5   27.0        Brown  Northeast           0.0      5     35        Brown   
6    NaN          NaN  Southwest           NaN      6     25        Black   
7   28.0        Black  Southeast           1.0      7     52        Brown   
8   21.0        Blond  Southeast           1.0      7     52        Brown   
9   23.0        Brown  Southeast           1.0      7     52        Brown   

   Validation_y  
0             1  
1             1  
2             1  
3             0  
4             0  
5             0  
6             0  
7             0  
8             0  
9             0

#### 15.	Split the below table and perform concat row wise and column wise

In [204]:
# Concat row wise the above splitted dataframe
pd.concat([df8,df9], axis = 0)

index  Age Hair Color  US Region  Validation
0      0   25      Black  Southwest           1
1      1   30      Black  Northwest           1
2      2   45        Red  Northeast           1
3      3   35      Blond  Southwest           0
4      4   33      Brown  Southwest           0
5      5   35      Brown  Northeast           0
6      6   25      Black  Southwest           0
7      7   52      Brown  Southeast           0
0      8   21      Blond  Southwest           1
1      9   24      Blond  Northeast           0
2     10   48      Black  Southwest           1
3     11   22      Black  Southwest           0
4     12   27      Brown  Northeast           0
5     13   28      Black  Southeast           1
6     14   21      Blond  Southeast           1
7     15   51      Black  Northwest           0
8     16   23      Brown  Southeast           1

In [205]:
# Concat column wise the above splitted dataframe
pd.concat([df8,df9],axis=1)

index   Age Hair Color  US Region  Validation  index  Age Hair Color  \
0    0.0  25.0      Black  Southwest         1.0      8   21      Blond   
1    1.0  30.0      Black  Northwest         1.0      9   24      Blond   
2    2.0  45.0        Red  Northeast         1.0     10   48      Black   
3    3.0  35.0      Blond  Southwest         0.0     11   22      Black   
4    4.0  33.0      Brown  Southwest         0.0     12   27      Brown   
5    5.0  35.0      Brown  Northeast         0.0     13   28      Black   
6    6.0  25.0      Black  Southwest         0.0     14   21      Blond   
7    7.0  52.0      Brown  Southeast         0.0     15   51      Black   
8    NaN   NaN        NaN        NaN         NaN     16   23      Brown   

   US Region  Validation  
0  Southwest           1  
1  Northeast           0  
2  Southwest           1  
3  Southwest           0  
4  Northeast           0  
5  Southeast           1  
6  Southeast           1  
7  Northwest           0  
8  Southeast           1